### PR TITLE
Carbonized Checkbox, Buttons, Number Input

### PR DESCRIPTION
**Pull request by FlorianRappl**
First part of the carbonization.

I replaced / changed:

- Buttons
- Checkbox
- Number input
- Panel with Show / Hide (replaced with Accordion, as this seems like its the closest to what we want)

I am not sure if I need to change the version or what the process is. Any advice would be appreciated!

Thanks!

image

image

image

### CODE REVIEW

**Comment by jonathandick** [comment]
I think we have this repo forked now in openmrs. I think we should use that. @donaldkibet what do you think?

**Comment by FlorianRappl** [comment]
I did not @jonathandick 

https://github.com/openmrs/openmrs-esm-form-entry/blob/master/package.json#L22

**Comment by donaldkibet** [comment]
@jonathandick the [openmrs-esm-form-entry](https://github.com/openmrs/openmrs-esm-form-entry) is basically form-entry converted into a micro-frontend, that still references this as mentioned by @FlorianRappl  above. we can fork [this repo](https://github.com/AMPATH/ngx-openmrs-formentry) for carbonising work to openmrs organization as a published version of this is still used by [ng2-amrs](https://github.com/ampath/ng2-amrs)

**Comment by FlorianRappl** [comment]
So whats the story now for this PR? @enyachoke

**Comment by donaldkibet** [comment]
> So whats the story now for this PR? @enyachoke

@FlorianRappl  the changes from this PR are merged into this branch [3.0.0 Carbon](https://github.com/AMPATH/ngx-openmrs-formentry/tree/3.0.0-carbonize).  which @enyachoke picked up from and continued to work on the carbon features

here is the [slack](https://openmrs.slack.com/archives/CHP5QAE5R/p1622094397091700) conversation that got us to create the carbon branch

I will go ahead and close this PR as the changes are already incorporated in the `3.0.0 carbon`  feel free to reopen it needed.

Thanks, @FlorianRappl

**Pull request closed without merging**
